// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7Hh9tjcMe8b4r55hF-hZ5xvqQPvkCGHU',
    appId: '1:167493739359:web:58030f38589aeaf5488cea',
    messagingSenderId: '167493739359',
    projectId: 'chatapp-40e99',
    authDomain: 'chatapp-40e99.firebaseapp.com',
    storageBucket: 'chatapp-40e99.appspot.com',
    measurementId: 'G-88NJR11B5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARNRWGajY9-2np6Tk4SYVLqAx4QbKGpnY',
    appId: '1:167493739359:android:7dc38c5f85fe4113488cea',
    messagingSenderId: '167493739359',
    projectId: 'chatapp-40e99',
    storageBucket: 'chatapp-40e99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASjhr6Cj-t-8xBCvHnFx6y0BHV7gAsm_0',
    appId: '1:167493739359:ios:9823b180162f23d5488cea',
    messagingSenderId: '167493739359',
    projectId: 'chatapp-40e99',
    storageBucket: 'chatapp-40e99.appspot.com',
    iosClientId: '167493739359-0vvgij2c3bic0o19ej61be1pkqrvh9ti.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASjhr6Cj-t-8xBCvHnFx6y0BHV7gAsm_0',
    appId: '1:167493739359:ios:9823b180162f23d5488cea',
    messagingSenderId: '167493739359',
    projectId: 'chatapp-40e99',
    storageBucket: 'chatapp-40e99.appspot.com',
    iosClientId: '167493739359-0vvgij2c3bic0o19ej61be1pkqrvh9ti.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
